apiVersion: v1
kind: Secret
metadata:
  name: volume-azurefile-storage-secret
type: Opaque
data:
  azurestorageaccountname: [c3RvcmFnZWpib3Nzazhz]
  azurestorageaccountkey: [bWtISlJES0pSNm9KMmxkaGR4ZjZUdG5aWlhJRitGTHVBcGdZTVhEUkY2YU83ZXhXVzlRU3BCV3BleHZwMDVTcDlQWWVoUlFsU1p3UU5TUGZDTmMzWmc9PQ==]