---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-azurefile-static
  namespace: sftp
provisioner: kubernetes.io/azure-file
#mountOptions:
#  - dir_mode=0755
#  - file_mode=0644
#  - uid=1000
#  - gid=500
#  - mfsymlinks
parameters:
  skuName: Standard_LRS
  storageAccount: storagejbossk8s